print('***********')
print('*         *')
print('*  O   O  *')
print('*         *')
print('*         *')
print('*         *')
print('***********')
print('  ||   ||  ')
print('  ||   ||  ')
print('  ==   ==  ')
